// create dummy news data
export const NEWS_DATA = [
  {
    id: "1",
    title: "Breaking News: Market Hits All-Time High",
    content:
      "The stock market reached an all-time high today, driven by strong earnings reports and positive economic data. Investors are optimistic about future growth, with many analysts predicting continued upward momentum. Experts caution, however, that market corrections are always possible, and advise diversification to mitigate potential risks. This historic milestone reflects both domestic and global economic trends, highlighting the resilience of the financial sector.",
    author: "John Doe",
    date: "2023-10-01",
    category: "Finance",
    source: "Reuters",
    image: "https://picsum.photos/400/200?random=1",
  },
  {
    id: "2",
    title: "Tech Stocks Rally as AI Takes Center Stage",
    content:
      "Technology stocks surged today as advancements in artificial intelligence captured investor attention. Major tech companies announced new AI-driven products and services, fueling excitement in the market. Industry leaders believe this trend will revolutionize various sectors, from healthcare to transportation. Despite some concerns about ethical implications, the overall sentiment remains positive, with experts forecasting significant growth in AI investments.",
    author: "Jane Smith",
    date: "2023-10-02",
    category: "Technology",
    source: "TechCrunch",
    image: "https://picsum.photos/400/200?random=2",
  },
  {
    id: "3",
    title: "Global Markets React to Economic Uncertainty",
    content:
      "Global markets experienced volatility today as investors reacted to mixed economic signals. Fluctuations in currency values and commodity prices contributed to the uncertainty. Economists point to ongoing geopolitical tensions and shifting trade policies as key factors influencing market behavior. While some investors remain cautious, others see opportunities for strategic investments during periods of instability. Market analysts recommend closely monitoring global developments.",
    author: "Alice Johnson",
    date: "2022-10-03",
    category: "World",
    source: "BBC News",
    image: "https://picsum.photos/400/200?random=3",
  },
  {
    id: "4",
    title: "Sports Update: Local Team Wins Championship",
    content:
      "The local football team clinched the championship title after a thrilling final match. Fans celebrated the victory with parades and community events, highlighting the team's hard work and dedication throughout the season. Coaches praised the players for their teamwork and perseverance, while local businesses reported increased sales due to the festivities. The win has inspired young athletes across the region to pursue their sports dreams.",
    author: "Mike Brown",
    date: "2023-10-04",
    category: "Sports",
    source: "ESPN",
    image: "https://picsum.photos/400/200?random=4",
  },
  {
    id: "5",
    title: "Weather Alert: Heavy Rain Expected Tomorrow",
    content:
      "Meteorologists predict heavy rainfall in the region tomorrow, urging residents to take precautions. Local authorities have issued advisories for potential flooding in low-lying areas and recommend securing outdoor belongings. Emergency services are on standby to respond to any incidents. Commuters are advised to check traffic updates and plan for possible delays. The weather event is expected to last through the evening, with improving conditions by the weekend.",
    author: "Sara Lee",
    date: "2024-10-05",
    category: "Weather",
    source: "The Weather Channel",
    image: "https://picsum.photos/400/200?random=5",
  },
  {
    id: "6",
    title: "Health News: New Vaccine Shows Promise",
    content:
      "A new vaccine has shown promising results in early trials, offering hope for disease prevention. Researchers report high efficacy rates and minimal side effects among participants. Health officials are optimistic about the potential impact on public health, especially in vulnerable populations. Further studies are planned to confirm long-term effectiveness and safety. The development marks a significant step forward in medical science and global health initiatives.",
    author: "Dr. Emily White",
    date: "2023-10-06",
    category: "Health",
    source: "Medical News Today",
    image: "https://picsum.photos/400/200?random=6",
  },
  {
    id: "7",
    title: "Entertainment: Award Show Highlights",
    content:
      "Last night's award show featured stunning performances and surprise winners. Celebrities dazzled on the red carpet, showcasing the latest fashion trends. The event included emotional acceptance speeches and memorable musical acts, drawing praise from fans and critics alike. Organizers emphasized the importance of diversity and inclusion in the entertainment industry. The show concluded with a tribute to legendary artists who have shaped the field.",
    author: "Chris Evans",
    date: "2025-10-07",
    category: "Entertainment",
    source: "Variety",
    image: "https://picsum.photos/400/200?random=7",
  },
  {
    id: "8",
    title: "Science: Space Probe Sends New Images",
    content:
      "A space probe has sent back new images of a distant planet, exciting astronomers worldwide. The high-resolution photos reveal previously unseen surface features and atmospheric patterns. Scientists are analyzing the data to gain insights into the planet's composition and potential for supporting life. The mission represents a major achievement in space exploration, inspiring future research and international collaboration in the field of astronomy.",
    author: "Linda Green",
    date: "2024-10-08",
    category: "Science",
    source: "NASA",
    image: "https://picsum.photos/400/200?random=8",
  },
  {
    id: "9",
    title: "Politics: Election Campaigns Heat Up",
    content:
      "Political parties ramp up their campaigns as the election date approaches. Candidates are holding rallies, debates, and community meetings to connect with voters and share their platforms. Key issues include the economy, healthcare, and education reform. Analysts predict a close race, with voter turnout expected to be high. Election officials remind citizens to verify their registration and participate in the democratic process.",
    author: "Robert King",
    date: "2025-10-09",
    category: "Politics",
    source: "CNN",
    image: "https://picsum.photos/400/200?random=9",
  },
  {
    id: "10",
    title: "Travel: Top Destinations for 2024",
    content:
      "Travel experts have released a list of the top destinations to visit in 2024. The recommendations include both popular cities and hidden gems, offering something for every type of traveler. Highlights range from cultural festivals and natural wonders to culinary experiences and adventure sports. Industry insiders advise booking early to secure the best deals. Sustainable tourism practices are also emphasized for responsible travel.",
    author: "Anna Bell",
    date: "2025-10-10",
    category: "Travel",
    source: "Lonely Planet",
    image: "https://picsum.photos/400/200?random=10",
  },
  {
    id: "11",
    title: "Education: Schools Embrace Digital Learning",
    content:
      "Schools across the country are adopting digital learning platforms to enhance student engagement. Teachers report improved participation and access to resources, while students benefit from personalized learning experiences. Administrators highlight the importance of training and support for educators. The shift is expected to continue, with investments in technology and infrastructure on the rise.",
    author: "Priya Patel",
    date: "2025-10-11",
    category: "Education",
    source: "EdTech Magazine",
    image: "https://picsum.photos/400/200?random=11",
  },
  {
    id: "12",
    title: "Environment: City Launches Green Initiative",
    content:
      "The city council has launched a new green initiative aimed at reducing carbon emissions and promoting sustainability. Programs include expanded recycling, tree planting, and incentives for using public transportation. Residents are encouraged to participate in community clean-up events. Officials hope the initiative will serve as a model for other cities.",
    author: "Carlos Rivera",
    date: "2023-10-12",
    category: "Environment",
    source: "National Geographic",
    image: "https://picsum.photos/400/200?random=12",
  },
  {
    id: "13",
    title: "Business: Startup Secures Major Funding",
    content:
      "A local startup has secured major funding from venture capitalists, enabling expansion into new markets. The company plans to hire additional staff and invest in product development. Industry experts cite the startup's innovative approach and strong leadership as key factors in its success. The funding round was oversubscribed, reflecting investor confidence.",
    author: "Samantha Lee",
    date: "2023-10-13",
    category: "Business",
    source: "Forbes",
    image: "https://picsum.photos/400/200?random=13",
  },
  {
    id: "14",
    title: "Automotive: Electric Cars Gain Popularity",
    content:
      "Sales of electric cars have surged this year, driven by consumer demand for eco-friendly transportation. Automakers are introducing new models with longer ranges and faster charging times. Government incentives and improved infrastructure are also contributing to the trend. Analysts predict continued growth in the electric vehicle market.",
    author: "David Kim",
    date: "2023-10-14",
    category: "Automotive",
    source: "Car and Driver",
    image: "https://picsum.photos/400/200?random=14",
  },
  {
    id: "15",
    title: "Food: Local Restaurant Wins Culinary Award",
    content:
      "A local restaurant has won a prestigious culinary award for its innovative menu and exceptional service. The chef credits the team’s creativity and dedication to quality ingredients. Food critics praised the restaurant’s unique flavors and welcoming atmosphere. Reservations are now in high demand as food enthusiasts flock to try the award-winning dishes.",
    author: "Julia Chen",
    date: "2023-10-15",
    category: "Food",
    source: "Eater",
    image: "https://picsum.photos/400/200?random=15",
  },
  {
    id: "16",
    title: "Fashion: Fall Trends Take Over Runways",
    content:
      "Fashion designers unveiled their latest collections at this season’s runway shows, highlighting bold colors and sustainable fabrics. Industry insiders note a shift toward eco-conscious designs and inclusive sizing. Influencers and celebrities are already embracing the new trends, setting the tone for fall wardrobes everywhere.",
    author: "Olivia Martinez",
    date: "2023-10-16",
    category: "Fashion",
    source: "Vogue",
    image: "https://picsum.photos/400/200?random=16",
  },
  {
    id: "17",
    title: "Real Estate: Housing Market Remains Strong",
    content:
      "The housing market remains strong, with home prices continuing to rise in many regions. Low interest rates and high demand are fueling competition among buyers. Real estate agents advise acting quickly and being prepared for bidding wars. Experts expect the trend to persist through the end of the year.",
    author: "Marcus Allen",
    date: "2023-10-17",
    category: "Real Estate",
    source: "Zillow",
    image: "https://picsum.photos/400/200?random=17",
  },
  {
    id: "18",
    title: "Culture: Museum Opens New Exhibit",
    content:
      "A renowned museum has opened a new exhibit featuring rare artifacts and interactive displays. Visitors can explore the history and cultural significance of the collection. Curators hope the exhibit will inspire curiosity and appreciation for the arts. Special events and workshops are scheduled throughout the month.",
    author: "Fatima Hassan",
    date: "2023-10-18",
    category: "Culture",
    source: "Smithsonian",
    image: "https://picsum.photos/400/200?random=18",
  },
  {
    id: "19",
    title: "Economy: Job Growth Exceeds Expectations",
    content:
      "Recent reports show job growth exceeding expectations, with gains across multiple sectors. Economists attribute the positive trend to increased consumer spending and business investment. Unemployment rates have fallen, and wages are rising in several industries. Policymakers are optimistic about continued economic recovery.",
    author: "Liam O'Connor",
    date: "2023-10-19",
    category: "Economy",
    source: "Bloomberg",
    image: "https://picsum.photos/400/200?random=19",
  },
  {
    id: "20",
    title: "Technology: Cybersecurity Threats on the Rise",
    content:
      "Cybersecurity experts warn of a rise in online threats targeting businesses and individuals. Recent incidents include data breaches and ransomware attacks. Organizations are urged to strengthen their security protocols and educate employees about best practices. The public is reminded to use strong passwords and remain vigilant online.",
    author: "Sophia Turner",
    date: "2023-10-20",
    category: "Technology",
    source: "Wired",
    image: "https://picsum.photos/400/200?random=20",
  },
  // --- Additional 30 dummy news items ---
  {
    id: "21",
    title: "Finance: Cryptocurrency Market Sees Volatility",
    content:
      "Cryptocurrency prices fluctuated sharply today as investors responded to regulatory news and market speculation. Analysts recommend caution and thorough research before making investment decisions.",
    author: "Ethan Brooks",
    date: "2022-11-01",
    category: "Finance",
    source: "CoinDesk",
    image: "https://picsum.photos/400/200?random=21",
  },
  {
    id: "22",
    title: "Technology: Quantum Computing Breakthrough",
    content:
      "Researchers announced a major breakthrough in quantum computing, potentially accelerating advancements in cryptography and data analysis. Industry leaders are watching closely for commercial applications.",
    author: "Maya Singh",
    date: "2022-12-02",
    category: "Technology",
    source: "MIT Tech Review",
    image: "https://picsum.photos/400/200?random=22",
  },
  {
    id: "23",
    title: "World: Peace Talks Resume in Conflict Zone",
    content:
      "International mediators have resumed peace talks in a long-standing conflict zone, raising hopes for a diplomatic resolution. Observers remain cautiously optimistic about the outcome.",
    author: "Ahmed Nasser",
    date: "2023-01-03",
    category: "World",
    source: "Al Jazeera",
    image: "https://picsum.photos/400/200?random=23",
  },
  {
    id: "24",
    title: "Sports: Marathon Runner Sets New Record",
    content:
      "A marathon runner broke the previous world record in a thrilling race, inspiring athletes worldwide. The event drew large crowds and significant media attention.",
    author: "Grace Kim",
    date: "2023-02-04",
    category: "Sports",
    source: "Runner's World",
    image: "https://picsum.photos/400/200?random=24",
  },
  {
    id: "25",
    title: "Weather: Heatwave Sweeps Across Europe",
    content:
      "A severe heatwave is affecting several European countries, with authorities urging residents to stay hydrated and avoid outdoor activities during peak hours.",
    author: "Luca Rossi",
    date: "2023-03-05",
    category: "Weather",
    source: "BBC Weather",
    image: "https://picsum.photos/400/200?random=25",
  },
  {
    id: "26",
    title: "Health: Mental Wellness Campaign Launched",
    content:
      "A new mental wellness campaign aims to raise awareness and provide resources for those struggling with mental health issues. Community leaders encourage open conversations.",
    author: "Nina Patel",
    date: "2023-04-06",
    category: "Health",
    source: "WHO",
    image: "https://picsum.photos/400/200?random=26",
  },
  {
    id: "27",
    title: "Entertainment: Indie Film Wins Festival Award",
    content:
      "An independent film has won the top prize at a major film festival, earning praise for its storytelling and direction. The filmmakers hope for wider distribution.",
    author: "Oscar Lee",
    date: "2023-05-07",
    category: "Entertainment",
    source: "Hollywood Reporter",
    image: "https://picsum.photos/400/200?random=27",
  },
  {
    id: "28",
    title: "Science: New Species Discovered in Amazon",
    content:
      "Scientists have discovered a new species of amphibian in the Amazon rainforest, highlighting the region's biodiversity and the importance of conservation efforts.",
    author: "Maria Gomez",
    date: "2023-06-08",
    category: "Science",
    source: "Nature",
    image: "https://picsum.photos/400/200?random=28",
  },
  {
    id: "29",
    title: "Politics: Parliament Approves New Bill",
    content:
      "The national parliament has approved a new bill aimed at improving infrastructure and public services. Lawmakers say the legislation will benefit communities nationwide.",
    author: "Tomislav Novak",
    date: "2023-07-09",
    category: "Politics",
    source: "Reuters",
    image: "https://picsum.photos/400/200?random=29",
  },
  {
    id: "30",
    title: "Travel: Airlines Expand International Routes",
    content:
      "Major airlines are expanding their international routes as travel demand rebounds. Passengers are advised to check updated schedules and entry requirements.",
    author: "Emily Carter",
    date: "2023-08-10",
    category: "Travel",
    source: "Travel Weekly",
    image: "https://picsum.photos/400/200?random=30",
  },
  {
    id: "31",
    title: "Education: University Launches Online Degrees",
    content:
      "A leading university has launched a suite of online degree programs, making higher education more accessible to students worldwide.",
    author: "James Wilson",
    date: "2023-09-11",
    category: "Education",
    source: "Inside Higher Ed",
    image: "https://picsum.photos/400/200?random=31",
  },
  {
    id: "32",
    title: "Environment: Wildlife Reserve Expands",
    content:
      "A major wildlife reserve has expanded its protected area, providing new habitats for endangered species and supporting biodiversity.",
    author: "Chloe Dubois",
    date: "2023-10-12",
    category: "Environment",
    source: "WWF",
    image: "https://picsum.photos/400/200?random=32",
  },
  {
    id: "33",
    title: "Business: Retailers Report Strong Holiday Sales",
    content:
      "Retailers are reporting strong holiday sales, driven by consumer confidence and promotional events. Analysts expect the trend to continue through the season.",
    author: "Henry Clark",
    date: "2023-11-13",
    category: "Business",
    source: "CNBC",
    image: "https://picsum.photos/400/200?random=33",
  },
  {
    id: "34",
    title: "Automotive: Autonomous Vehicles Tested in City",
    content:
      "Autonomous vehicles are being tested on city streets as part of a pilot program. Officials are monitoring safety and public feedback.",
    author: "Sofia Andersson",
    date: "2023-12-14",
    category: "Automotive",
    source: "The Verge",
    image: "https://picsum.photos/400/200?random=34",
  },
  {
    id: "35",
    title: "Food: Farmers Market Promotes Local Produce",
    content:
      "A new farmers market is promoting local produce and sustainable agriculture. Shoppers can enjoy fresh fruits, vegetables, and artisanal goods.",
    author: "Lucas Meyer",
    date: "2024-01-15",
    category: "Food",
    source: "Bon Appétit",
    image: "https://picsum.photos/400/200?random=35",
  },
  {
    id: "36",
    title: "Fashion: Designer Collaborates with Artists",
    content:
      "A renowned fashion designer has collaborated with local artists to create a unique clothing line, blending art and style.",
    author: "Isabella Rossi",
    date: "2024-02-16",
    category: "Fashion",
    source: "Elle",
    image: "https://picsum.photos/400/200?random=36",
  },
  {
    id: "37",
    title: "Real Estate: Urban Development Project Announced",
    content:
      "City officials have announced a new urban development project aimed at revitalizing downtown areas and creating affordable housing.",
    author: "Noah Johnson",
    date: "2024-03-17",
    category: "Real Estate",
    source: "Urban Land",
    image: "https://picsum.photos/400/200?random=37",
  },
  {
    id: "38",
    title: "Culture: Festival Celebrates Local Heritage",
    content:
      "A cultural festival is celebrating local heritage with music, dance, and traditional cuisine. Organizers hope to foster community pride.",
    author: "Aisha Khan",
    date: "2024-04-18",
    category: "Culture",
    source: "Smithsonian",
    image: "https://picsum.photos/400/200?random=38",
  },
  {
    id: "39",
    title: "Economy: Inflation Rates Stabilize",
    content:
      "Recent data shows inflation rates stabilizing after months of volatility. Economists are cautiously optimistic about future growth.",
    author: "Benjamin Lee",
    date: "2024-05-19",
    category: "Economy",
    source: "Financial Times",
    image: "https://picsum.photos/400/200?random=39",
  },
  {
    id: "40",
    title: "Technology: 5G Networks Expand Nationwide",
    content:
      "Telecom companies are expanding 5G networks nationwide, promising faster speeds and improved connectivity for consumers.",
    author: "Samantha Brown",
    date: "2024-06-20",
    category: "Technology",
    source: "CNET",
    image: "https://picsum.photos/400/200?random=40",
  },
  {
    id: "41",
    title: "Finance: Central Bank Adjusts Interest Rates",
    content:
      "The central bank has adjusted interest rates in response to economic indicators, aiming to balance growth and inflation.",
    author: "Oliver Smith",
    date: "2024-07-21",
    category: "Finance",
    source: "Wall Street Journal",
    image: "https://picsum.photos/400/200?random=41",
  },
  {
    id: "42",
    title: "Technology: Startups Innovate in Green Tech",
    content:
      "Startups are driving innovation in green technology, developing solutions for renewable energy and sustainable living.",
    author: "Leah Kim",
    date: "2024-08-22",
    category: "Technology",
    source: "TechCrunch",
    image: "https://picsum.photos/400/200?random=42",
  },
  {
    id: "43",
    title: "World: Humanitarian Aid Reaches Refugees",
    content:
      "International organizations have delivered humanitarian aid to refugees in crisis zones, providing food, shelter, and medical care.",
    author: "Mohammed Ali",
    date: "2024-09-23",
    category: "World",
    source: "UN News",
    image: "https://picsum.photos/400/200?random=43",
  },
  {
    id: "44",
    title: "Sports: National Team Qualifies for Finals",
    content:
      "The national team has qualified for the finals in a major tournament, sparking celebrations among fans and players.",
    author: "Emma Johansson",
    date: "2024-10-24",
    category: "Sports",
    source: "ESPN",
    image: "https://picsum.photos/400/200?random=44",
  },
  {
    id: "45",
    title: "Weather: Snowstorm Disrupts Travel",
    content:
      "A severe snowstorm has disrupted travel across several states, with authorities urging caution and providing emergency services.",
    author: "Jack Miller",
    date: "2024-11-25",
    category: "Weather",
    source: "The Weather Channel",
    image: "https://picsum.photos/400/200?random=45",
  },
  {
    id: "46",
    title: "Health: Breakthrough in Cancer Research",
    content:
      "Scientists have announced a breakthrough in cancer research, offering new hope for treatment and prevention.",
    author: "Dr. Laura Chen",
    date: "2024-12-26",
    category: "Health",
    source: "Medical News Today",
    image: "https://picsum.photos/400/200?random=46",
  },
  {
    id: "47",
    title: "Entertainment: Streaming Service Launches Originals",
    content:
      "A popular streaming service has launched a slate of original series and films, attracting subscribers with exclusive content.",
    author: "Ryan Davis",
    date: "2025-01-27",
    category: "Entertainment",
    source: "Variety",
    image: "https://picsum.photos/400/200?random=47",
  },
  {
    id: "48",
    title: "Science: Ocean Exploration Reveals New Species",
    content:
      "Marine biologists have discovered new species during a deep-sea exploration mission, expanding our understanding of ocean life.",
    author: "Sophie Martin",
    date: "2025-02-28",
    category: "Science",
    source: "National Geographic",
    image: "https://picsum.photos/400/200?random=48",
  },
  {
    id: "49",
    title: "Politics: Election Results Announced",
    content:
      "Election officials have announced the results of the national election, with the winning party pledging to address key issues.",
    author: "Carlos Fernandez",
    date: "2025-03-29",
    category: "Politics",
    source: "CNN",
    image: "https://picsum.photos/400/200?random=49",
  },
  {
    id: "50",
    title: "Travel: Eco-Tourism Destinations Gain Popularity",
    content:
      "Eco-tourism destinations are gaining popularity among travelers seeking sustainable and responsible travel experiences.",
    author: "Natalie Green",
    date: "2025-04-30",
    category: "Travel",
    source: "Lonely Planet",
    image: "https://picsum.photos/400/200?random=50",
  },
];
