import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components";
import { ToastProvider } from "@/providers/ToastProvider";

export const metadata: Metadata = {
  title: "Next Js Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-dvh flex-col ">
        <Header className="sticky top-0 z-50" />
        <main className="bg-gray-50 flex-1 overflow-y-auto max-w-7xl mx-auto w-full">
          <ToastProvider>{children}</ToastProvider>
        </main>
      </body>
    </html>
  );
}
